# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY mcp.json .
COPY README.md .
COPY LICENSE .
COPY src ./src

# Install dependencies
RUN pip install --no-cache-dir .

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Default command to run MCP server
CMD ["python", "-m", "fujitsu_sdt_mcp.server"]
